#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# ///
"""Reconcile the canonical Page Coverage Matrix (C-UX-Scenarios/00-ux-scenarios.md) with the
wds-8-product-evolution scenarios (evolution/scenarios/*.md) that are already implemented in
production but never made it into the canonical WDS doc.

Story E16.3 (T3.2 + T3.4, ideias/epics-onda-5.md). Closes the residual half of PRD 05 §4.2/FR-2
that Story E1.2 deliberately deferred: E1.2 taught /bagual-qa-builder to translate evolution
scenarios into page->scenario->purpose rows, but only inside the qa-pack's own internal
"Evolution-sourced Coverage Matrix additions" table (context/changelog) -- it explicitly never
wrote into the canonical scenarios_source, citing "this skill distills WDS design truth, it never
rewrites it" (see _bmad/custom/bagual-qa-builder.toml). This script closes that residual gap the
way FR-2's original text intended ("normalize them INTO the Coverage Matrix of 00-ux-scenarios.md")
without reopening the F19-hardened prohibition against inventing/rewriting hand-authored design
truth (PRD 05 §4.2): it only ever touches ONE delimited, auto-generated appendix section, appended
after (never inside) the 5 hand-authored canonical scenarios' Page Coverage Matrix; it never edits
a byte outside the delimiters; and every row is a mechanical transcription of already `status:
approved`, already-shipped wds-8 scenario files -- never an invented or judged addition. This is a
routing/filing fix for wds-8's own already-approved output (via i, already passed through design),
not a "via ii small-change" bypass of design (PRD 05 F19) -- the design already happened; this
script only repairs the fact that its output landed in the wrong tree (evolution/scenarios/,
hardcoded, PRD 05 §4.2) instead of the canonical one.

REFORMULATED 2026-07-12 (Story E16.3 rework, owner decision): this script's logic and CLI are
UNCHANGED (still stdlib-only, still generic, still takes --scenarios-source/--evolution-dir as
plain arguments -- it never hardcoded a caller). What changed is WHO invokes it. The first pass of
E16.3 wired it into `_bmad/custom/bagual-qa-builder.toml`, reasoning (see the paragraph above) that
a mechanical, delimited, read-only-preserving write-back wasn't "rewriting design truth". On
review, that was still a F19 violation: F19 (`ideias/prd-05-wds.md` §4.2) draws the line at WHO may
write a scenario/Coverage Matrix page, not at how careful the write is -- only via (i) (`wds-8`)
may. This script is now invoked by `wds-8-product-evolution` itself, via the override
`_bmad/custom/wds-8-product-evolution.toml`, right after workflow-scope.md Step 5 approves a
scenario -- wds-8 filing its own already-approved output into the canonical doc it belongs in.
`bagual-qa-builder` is read-only of `{scenarios_source}` again, exactly as Story E1.2 first decided.

Idempotent by construction: the appendix is produced deterministically from the current content of
`evolution/scenarios/*.md` + the canonical Page Coverage Matrix (no wall-clock timestamp embedded),
and a second run with unchanged inputs regenerates byte-identical content between the same two
delimiter markers -- `--check` reports whether a run would change anything without writing.

Usage:
    reconcile_evolution_coverage.py --scenarios-source PATH --evolution-dir DIR [--check] [--verbose]

Exit codes: 0 = ok (written or already reconciled) · 1 = --check found pending changes · 2 = error.
"""
from __future__ import annotations

import argparse
import re
import sys
import unicodedata
from pathlib import Path

BEGIN_MARKER = "<!-- BEGIN evolution-coverage-writeback (auto-generated by reconcile_evolution_coverage.py, invoked by wds-8-product-evolution's via-i override _bmad/custom/wds-8-product-evolution.toml -- story E16.3/T3.4, reformulated 2026-07-12; do not hand-edit inside these markers, they are replaced wholesale on every reconciliation run) -->"
END_MARKER = "<!-- END evolution-coverage-writeback -->"

_CANONICAL_TABLE_HEADER = "## Page Coverage Matrix"
_TABLE_ROW_RE = re.compile(r"^\|\s*(.+?)\s*\|\s*(.+?)\s*\|\s*(.+?)\s*\|\s*$")

# Bullets under "**Pages affected:**" that describe wiring (menu/route registration), not a page
# itself, are skipped -- same "skip a non-page artifact" rule bagual-qa-builder.toml's
# persistent_facts already documents for the qa-pack-internal translation (Story E1.2).
_NON_PAGE_FILENAME_HINTS = ("App.tsx", "Layout.tsx")
_NON_PAGE_TEXT_HINTS = (
    "mantido",
    "mantidos",
    "mantida",
    "mantidas",
    "retirad",
    "sem alteração",
    "sem nenhuma alteração",
    "intocado",
    "intocados",
    "intocada",
)

# An explicit "this is a brand-new page" signal in the bullet's own prose -- when present, skip
# matching against the canonical Page Coverage Matrix entirely and derive a fresh label straight
# from the filename/route (matching a genuinely new page against existing canonical labels risks
# false positives from incidental word overlap, e.g. "admin").
_NEW_PAGE_PREFIXES = ("nova página", "nova tela", "new page")

# Generic/overused tokens (path scaffolding, tech nouns) that must NOT count on their own toward a
# canonical-page match -- e.g. almost every admin bullet's path contains "admin", which would
# otherwise false-match anything under "Dashboard Admin". Meaningful domain words (usuarios,
# parceiros, dashboard, banners, proposals, ...) are deliberately NOT in this list.
_GENERIC_MATCH_STOPWORDS = {
    "admin", "frontend", "src", "features", "page", "pages", "tsx", "app", "novo", "nova",
    "novos", "novas", "tela", "telas", "nome", "modulo", "rota", "item", "menu", "lateral",
    "equivalente", "ou", "existente", "atual",
}

# Small, explicit, human-maintained bridge between English component/route tokens and the
# Portuguese canonical page labels of 00-ux-scenarios.md -- a plain normalization/synonym table
# (not a hidden judgment call): pure lexical overlap can't bridge `user-management/` <-> "Usuários"
# on its own. Extend this table, don't hardcode per-scenario logic, when future evolution
# scenarios need it.
_LABEL_SYNONYMS: dict[str, list[str]] = {
    "usuarios": ["user-management", "user management", "usermanagement", "users"],
    "parceiros": ["partners"],
    "dashboard parceiro": ["dashboard", "home", "homepage"],
}

_QUOTED_RE = re.compile(r'["‘’“”\']([^"‘’“”\']{2,40})["‘’“”\']')


def _strip_accents(s: str) -> str:
    return "".join(c for c in unicodedata.normalize("NFD", s) if unicodedata.category(c) != "Mn")


def _normalize_words(s: str) -> set[str]:
    s = _strip_accents(s).lower()
    # split camelCase / kebab / snake / path separators into words
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", s)
    s = re.sub(r"[^a-z0-9]+", " ", s)
    words = {w for w in s.split() if len(w) >= 3 and w not in {"tsx", "page", "pages", "new", "nova"}}
    return words


def load_canonical_pages(scenarios_source: Path) -> list[str]:
    """Extract the ordered, de-duplicated Page column of the canonical Page Coverage Matrix."""
    text = scenarios_source.read_text(encoding="utf-8")
    idx = text.find(_CANONICAL_TABLE_HEADER)
    if idx == -1:
        return []
    tail = text[idx:]
    pages: list[str] = []
    in_table = False
    for line in tail.splitlines():
        if line.strip().startswith("| Page "):
            in_table = True
            continue
        if in_table and line.strip().startswith("|---"):
            continue
        if in_table and line.strip().startswith("|"):
            m = _TABLE_ROW_RE.match(line)
            if m:
                page = m.group(1).strip()
                if page and page not in pages:
                    pages.append(page)
            continue
        if in_table and not line.strip().startswith("|"):
            break
    return pages


def _extract_section(text: str, header: str) -> str:
    """Body of a `## header` section, up to the next `## `-level header."""
    pattern = re.compile(rf"^##\s+{re.escape(header)}\s*$", re.MULTILINE)
    m = pattern.search(text)
    if not m:
        return ""
    start = m.end()
    nxt = re.search(r"^##\s+\S", text[start:], re.MULTILINE)
    return text[start : start + nxt.start()] if nxt else text[start:]


def _extract_h1(text: str) -> str:
    m = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    return m.group(1).strip() if m else ""


def _extract_frontmatter_title(text: str) -> str:
    m = re.search(r"^---\s*\n(.*?)\n---\s*\n", text, re.DOTALL)
    if not m:
        return ""
    fm = m.group(1)
    tm = re.search(r'^title:\s*"?(.+?)"?\s*$', fm, re.MULTILINE)
    return tm.group(1).strip() if tm else ""


def _first_sentence_or_bullet(section_text: str) -> str:
    section_text = section_text.strip()
    if not section_text:
        return ""
    # Prefer the first bullet if the section leads with a list; else the first sentence.
    lines = [l for l in section_text.splitlines() if l.strip()]
    if lines and lines[0].strip().startswith(("- ", "* ")):
        return lines[0].strip().lstrip("-*").strip()
    para = section_text.split("\n\n", 1)[0].replace("\n", " ").strip()
    m = re.search(r"^(.+?[.!?])(\s|$)", para)
    return (m.group(1) if m else para).strip()


def _pages_affected_bullets(scope_text: str) -> list[str]:
    m = re.search(r"\*\*Pages affected:\*\*\s*\n(.*?)(?=\n\*\*|\Z)", scope_text, re.DOTALL)
    if not m:
        return []
    block = m.group(1)
    bullets, current = [], None
    for line in block.splitlines():
        if line.strip().startswith(("- ", "* ")):
            if current is not None:
                bullets.append(current.strip())
            current = line.strip().lstrip("-*").strip()
        elif current is not None and line.strip():
            current += " " + line.strip()
    if current is not None:
        bullets.append(current.strip())
    return bullets


def _is_non_page_bullet(bullet: str) -> bool:
    if any(hint in bullet for hint in _NON_PAGE_FILENAME_HINTS):
        return True
    lowered = bullet.lower()
    return any(hint in lowered for hint in _NON_PAGE_TEXT_HINTS)


def _fresh_label(bullet: str) -> str:
    """Derive a readable label straight from a quoted path/filename -- used whenever the bullet
    declares itself a brand-new page, so it's never confused with an existing canonical one."""
    path_m = re.search(r"`([\w./-]+)`", bullet)
    token = path_m.group(1) if path_m else bullet
    base = Path(token).stem
    base = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", base)
    base = re.sub(r"[-_]+", " ", base)
    base = re.sub(r"\bPage\b", "", base, flags=re.IGNORECASE).strip()
    label = " ".join(w.capitalize() for w in base.split()) or "Página não identificada"
    is_admin = "admin" in token.lower() or "features-admin" in bullet
    if is_admin:
        label = re.sub(r"^Admin\s*", "", label).strip() or label
        label = f"Admin — {label}"
    return label


def _derive_label(bullet: str, canonical_pages: list[str]) -> str:
    lowered = bullet.lower()

    # 0. Explicit "brand-new page" signal -- never matched against existing canonical labels,
    #    to avoid false positives from incidental word overlap (e.g. "admin").
    if any(lowered.startswith(p) or f" {p}" in lowered[:60] for p in _NEW_PAGE_PREFIXES):
        return _fresh_label(bullet)

    words = _normalize_words(bullet)

    # 1. A quoted label in the bullet's own prose that matches a canonical page name exactly
    #    (accent/case-insensitive) is the highest-confidence signal -- the scenario author named
    #    the target screen verbatim (e.g. `vira a tela única "Usuários"`).
    canon_by_key = {" ".join(sorted(_normalize_words(c))): c for c in canonical_pages}
    for quoted in _QUOTED_RE.findall(bullet):
        key = " ".join(sorted(_normalize_words(quoted)))
        if key and key in canon_by_key:
            return canon_by_key[key]

    # 2. Explicit synonym bridge against canonical labels.
    for canon in canonical_pages:
        canon_key = " ".join(sorted(_normalize_words(canon)))
        for key, synonyms in _LABEL_SYNONYMS.items():
            if key == canon_key or key in _normalize_words(canon):
                if any(_normalize_words(syn) & words for syn in synonyms):
                    return canon

    # 3. Lexical overlap against canonical labels, ignoring generic/overused tokens that would
    #    otherwise false-match almost anything (e.g. "admin").
    significant_words = words - _GENERIC_MATCH_STOPWORDS
    best_page, best_overlap = "", 0
    for canon in canonical_pages:
        canon_words = _normalize_words(canon) - _GENERIC_MATCH_STOPWORDS
        overlap = len(canon_words & significant_words)
        if overlap > best_overlap:
            best_page, best_overlap = canon, overlap
    if best_overlap >= 1:
        return best_page

    # 4. No confident match and no explicit "new page" signal -- still derive a fresh label
    #    rather than silently dropping it (never invent a canonical match we don't have evidence
    #    for; the caller records this bullet's page as best-effort, not gap-worthy, since a page
    #    row -- possibly imprecisely labeled -- is still more useful than silently omitting it).
    return _fresh_label(bullet)


def build_rows(evolution_dir: Path, canonical_pages: list[str], verbose: bool = False) -> tuple[list[tuple[str, str, str, str]], list[str]]:
    rows: list[tuple[str, str, str, str]] = []
    gaps: list[str] = []
    for path in sorted(evolution_dir.glob("*.md")):
        text = path.read_text(encoding="utf-8", errors="replace")
        title = _extract_h1(text) or _extract_frontmatter_title(text) or path.stem
        scope = _extract_section(text, "Scope")
        bullets = [b for b in _pages_affected_bullets(scope) if not _is_non_page_bullet(b)]
        desired = _extract_section(text, "Desired State")
        success = _extract_section(text, "Success Criteria")
        purpose = _first_sentence_or_bullet(desired)
        success_bit = _first_sentence_or_bullet(success)
        if success_bit and success_bit not in purpose:
            purpose = f"{purpose} {success_bit}" if purpose else success_bit
        purpose = purpose.strip() or "[gap: nem Desired State nem Success Criteria puderam ser resumidos]"

        if not bullets:
            gaps.append(f"{path.name}: nenhuma página resolvida em ## Scope -> **Pages affected:**")
            continue

        source_rel = "_bmad-output/" + str(path.relative_to(evolution_dir.parents[1]))
        seen_labels: set[str] = set()
        for bullet in bullets:
            label = _derive_label(bullet, canonical_pages)
            if (label, title) in {(r[0], r[1]) for r in rows}:
                continue
            seen_labels.add(label)
            rows.append((label, f"Evolução — {title}", purpose, source_rel))
        if verbose:
            print(f"{path.name}: {len(seen_labels)} page row(s)", file=sys.stderr)
    return rows, gaps


def render_block(rows: list[tuple[str, str, str, str]], gaps: list[str]) -> str:
    lines = [BEGIN_MARKER, ""]
    lines.append(
        "## Page Coverage Matrix — Evolution-sourced additions (wds-8 via-i, reconciled by "
        "`reconcile_evolution_coverage.py`, Story E16.3/T3.4)"
    )
    lines.append("")
    lines.append(
        "> Additive appendix, never a rewrite of the 5 hand-authored canonical scenarios above. "
        "Each row below is a mechanical transcription of an already `status: approved`, "
        "already-shipped `wds-8-product-evolution` scenario file "
        "(`_bmad-output/evolution/scenarios/`) — never invented, never judged design content. "
        "Maintained by `wds-8-product-evolution` itself (override "
        "`_bmad/custom/wds-8-product-evolution.toml`), per PRD 05 F19 — `bagual-qa-builder` only "
        "reads this file, it never writes to it. Regenerated wholesale on every reconciliation "
        "run; hand-edits inside these markers do not persist."
    )
    lines.append("")
    lines.append("| Page | Scenario | Purpose in Flow | Source |")
    lines.append("|------|----------|------------------|--------|")
    for page, scenario, purpose, source in rows:
        lines.append(f"| {page} | {scenario} | {purpose} | `{source}` |")
    lines.append("")
    lines.append(f"**Evolution coverage:** {len(rows)} row(s) reconciled from {len({r[3] for r in rows})} evolution scenario file(s).")
    if gaps:
        lines.append("")
        lines.append("**Gaps (seen, not normalized — needs manual follow-up):**")
        for gap in gaps:
            lines.append(f"- {gap}")
    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines)


def reconcile(scenarios_source: Path, evolution_dir: Path, check: bool = False, verbose: bool = False) -> int:
    if not evolution_dir.exists():
        if verbose:
            print(f"evolution dir missing, nothing to reconcile: {evolution_dir}", file=sys.stderr)
        return 0
    canonical_pages = load_canonical_pages(scenarios_source)
    rows, gaps = build_rows(evolution_dir, canonical_pages, verbose)
    block = render_block(rows, gaps)

    text = scenarios_source.read_text(encoding="utf-8")
    if BEGIN_MARKER in text and END_MARKER in text:
        pattern = re.compile(re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL)
        new_text = pattern.sub(block, text)
    else:
        anchor = "\n---\n\n## Next Phase"
        if anchor in text:
            new_text = text.replace(anchor, f"\n---\n\n{block}\n\n---\n\n## Next Phase", 1)
        else:
            new_text = text.rstrip("\n") + f"\n\n---\n\n{block}\n"

    changed = new_text != text
    if check:
        if verbose:
            print("would change" if changed else "already reconciled (no-op)", file=sys.stderr)
        return 1 if changed else 0

    if changed:
        scenarios_source.write_text(new_text, encoding="utf-8")
        if verbose:
            print(f"wrote {scenarios_source} ({len(rows)} row(s))", file=sys.stderr)
    elif verbose:
        print("already reconciled (no-op)", file=sys.stderr)
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--scenarios-source", required=True, help="path to C-UX-Scenarios/00-ux-scenarios.md")
    ap.add_argument("--evolution-dir", required=True, help="path to evolution/scenarios/ directory")
    ap.add_argument("--check", action="store_true", help="dry-run: exit 1 if a write would change the file")
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args(argv)

    try:
        return reconcile(Path(args.scenarios_source), Path(args.evolution_dir), args.check, args.verbose)
    except Exception as e:  # noqa: BLE001 — surface any unexpected failure as exit 2
        print(f"error: {e}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
